D_net: Discriminator
G_net: Generator
L_pretrained: emore_recognition.pth
P_pretrained: pose_precise_gray.pth.tar
batch_size: 2
beta1: 0.5
beta2: 0.999
c2_dim: 13
c_dim: 240
d_conv_dim: 64
d_lr: 0.0001
d_repeat_num: 6
d_train_repeat: 1
display_f: 300
expression_w: 1.0
face_crop_size: 112
face_image_path: /home/frank/data/dataset/face_dataset/imgs_casia_rgb
face_image_pathB: /home/frank/data/dataset/face_dataset
face_image_path_val: data/test_pose
g_conv_dim: 16
g_lr: 0.0001
g_repeat_num: 6
g_train_repeat: 1
gray: true
image_size: 115
lambda_cls: 1.0
lambda_cls_id: 1.0
lambda_gp: 10.0
lambda_id_l2: 8.0
lambda_identical: 5.0
lambda_identity: 0.3
lambda_pose_l2: 6.0
lambda_pose_symmetry: 5.0
lambda_rec: 5.0
logs_path: v20/logs
loss_cls_id: false
loss_identity: true
loss_pose_symmetry: false
loss_rec: true
loss_rec_with_mask: true
mode: train
model_save_path: v20/models
norm: batch
num_epochs: 30
num_epochs_decay: 15
num_workers: 2
pretrained_model: ''
result_path: v20/results
sample_path: v20/samples
save_dir: v20
single_out: true
taget_pose: data/ref_pie_pose
test_mode: norm
test_model: 11-11
test_single_path: /home/kangyu/Dataset/pose_9a_new
use_pose_numbers: 1
visualize: false
