export CUDA_VISIBLE_DEVICES=0
python3 main.py \
--mode="test_celebA_5images" \
--batch_size=5 \
--save_dir="v20" \
--L_pretrained="emore_recognition.pth" \
--P_pretrained="pose_precise_gray.pth.tar" \
--lambda_id_l2=8.0 \
--d_train_repeat=1 \
--gray="True" \
--num_epochs=30 \
--num_epochs_decay=15 \
--loss_rec_with_mask="True" \
--c_dim=240 \
--expression_w=1.0 \
--face_image_path="samples/RAW" \
--test_single_path="samples/aug" \
--taget_pose='data/ref_pie_pose' \
--test_mode='aug' \
--use_pose_numbers=3